### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

## torch.from_array() / tensor.numpy()

In [4]:
# Example 1 - ### # 創建tensor ###
a = torch.randn((2,3))
b = torch.randn(3)

print(a.shape, b.shape)
a, b

torch.Size([2, 3]) torch.Size([3])


(tensor([[ 0.4017,  0.7373,  2.3352],
         [-0.8971, -0.4160, -2.5371]]), tensor([ 0.5361, -0.7777, -0.5665]))

In [5]:
## 元素的相乘(element-wise)
t_mul1 = a * b
t_mul2 = torch.mul(a, b)
print(t_mul1.shape, t_mul2.shape)
t_mul1, t_mul2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[ 0.2153, -0.5734, -1.3230],
         [-0.4809,  0.3235,  1.4373]]), tensor([[ 0.2153, -0.5734, -1.3230],
         [-0.4809,  0.3235,  1.4373]]))

In [6]:
# Example 2 - ### 矩陣乘法 ###
c = torch.randn((2,3))
d = torch.randn((3,4))

t_matmul1 = c.mm(d)
t_matmul2 = torch.mm(c,d)
t_matmul3 = torch.matmul(c,d)
t_matmul4 = c @ d

print(t_matmul1.shape, t_matmul2.shape, t_matmul3.shape, t_matmul4.shape)

t_matmul1, t_matmul2, t_matmul3, t_matmul4

torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4])


(tensor([[-0.1653,  1.1205, -0.7902, -0.4714],
         [-0.6524,  2.2892, -1.1906, -0.6731]]),
 tensor([[-0.1653,  1.1205, -0.7902, -0.4714],
         [-0.6524,  2.2892, -1.1906, -0.6731]]),
 tensor([[-0.1653,  1.1205, -0.7902, -0.4714],
         [-0.6524,  2.2892, -1.1906, -0.6731]]),
 tensor([[-0.1653,  1.1205, -0.7902, -0.4714],
         [-0.6524,  2.2892, -1.1906, -0.6731]]))

### Function 2 - your function to illustrate

## torch.reshape() / tensor.view()

In [7]:
# Example 1 - ### reshape ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
b = a.reshape(2, 6)
print(a.shape, b.shape)
a,b

torch.Size([2, 2, 3]) torch.Size([2, 6])


(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[5, 6, 7],
          [7, 8, 9]]]), tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]))

In [8]:
# Example 2 - ### view ###
c = a.view(2, 6)
print(a.shape, c.shape)
a,c

torch.Size([2, 2, 3]) torch.Size([2, 6])


(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[5, 6, 7],
          [7, 8, 9]]]), tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]))

In [ ]:
d = a.reshape(2, -1)
print(a.shape, d.shape)
a,d

### Function 3 - your function to illustrate

##　tensor.transpose() / tensor.permute()

In [9]:
# Example 1 - ### permute ### ## 變換 tensor 維度
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
e = a.permute((0, 2, 1))
print(a.shape, e.shape)
a, e

torch.Size([2, 2, 3]) torch.Size([2, 3, 2])


(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[5, 6, 7],
          [7, 8, 9]]]), tensor([[[1, 3],
          [2, 4],
          [3, 5]],
 
         [[5, 7],
          [6, 8],
          [7, 9]]]))

In [10]:
# Example 2 - ### your transpose ###
f = a.transpose(1,2)
print(a.shape, f.shape)
a, f

torch.Size([2, 2, 3]) torch.Size([2, 3, 2])


(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[5, 6, 7],
          [7, 8, 9]]]), tensor([[[1, 3],
          [2, 4],
          [3, 5]],
 
         [[5, 7],
          [6, 8],
          [7, 9]]]))

### Function 4 - your function to illustrate
＃＃　torch.unsqueeze() / torch.squeeze()



In [11]:
# Example 1 - ###  #增加維度在1的位置

a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
g = torch.unsqueeze(a, dim=1) #增加維度在1的位置
print(a.shape,g.shape)


torch.Size([2, 2, 3]) torch.Size([2, 1, 2, 3])


In [12]:
# Example 2 - #壓縮為度為1的位置

h = torch.squeeze(g) #壓縮為度為1的位置
print(g.shape,h.shape)

torch.Size([2, 1, 2, 3]) torch.Size([2, 2, 3])
